// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'serializers.dart';

// **************************************************************************
// BuiltValueGenerator
// **************************************************************************

Serializers _$serializers = (new Serializers().toBuilder()
      ..add(AccentureRecord.serializer)
      ..add(AccountantRecord.serializer)
      ..add(AdobexdRecord.serializer)
      ..add(AerospaceRecord.serializer)
      ..add(AftereffectsRecord.serializer)
      ..add(AiRecord.serializer)
      ..add(AirbnbRecord.serializer)
      ..add(AirtelRecord.serializer)
      ..add(AmazonRecord.serializer)
      ..add(AmdRecord.serializer)
      ..add(AndroidStudioRecord.serializer)
      ..add(AndroidquesRecord.serializer)
      ..add(AngularquesRecord.serializer)
      ..add(AppleRecord.serializer)
      ..add(AwsRecord.serializer)
      ..add(BehanceRecord.serializer)
      ..add(BigdataRecord.serializer)
      ..add(BlenderRecord.serializer)
      ..add(BlockchainRecord.serializer)
      ..add(BootstarpquesRecord.serializer)
      ..add(BudgetRecord.serializer)
      ..add(CanvaRecord.serializer)
      ..add(ChashquesRecord.serializer)
      ..add(ChemicalRecord.serializer)
      ..add(ChromeRecord.serializer)
      ..add(CivilRecord.serializer)
      ..add(CloudarchitectRecord.serializer)
      ..add(CognizantRecord.serializer)
      ..add(ComputerscienceRecord.serializer)
      ..add(CquesRecord.serializer)
      ..add(CssquesRecord.serializer)
      ..add(DartRecord.serializer)
      ..add(DataanalystRecord.serializer)
      ..add(DatabasemanagerRecord.serializer)
      ..add(DatascientistRecord.serializer)
      ..add(DevopsRecord.serializer)
      ..add(DiscordRecord.serializer)
      ..add(DjangoRecord.serializer)
      ..add(DropboxRecord.serializer)
      ..add(ElectricalRecord.serializer)
      ..add(ExpquesRecord.serializer)
      ..add(FacebookRecord.serializer)
      ..add(FigmaRecord.serializer)
      ..add(FinanceRecord.serializer)
      ..add(FinancialanalystRecord.serializer)
      ..add(FirebaseRecord.serializer)
      ..add(FlutterRecord.serializer)
      ..add(FresherquesRecord.serializer)
      ..add(FullstackdevRecord.serializer)
      ..add(GcpRecord.serializer)
      ..add(GitRecord.serializer)
      ..add(GoRecord.serializer)
      ..add(HrRecord.serializer)
      ..add(HrmanagerRecord.serializer)
      ..add(HtmlRecord.serializer)
      ..add(IllustratorRecord.serializer)
      ..add(IotRecord.serializer)
      ..add(ItmanagerRecord.serializer)
      ..add(JavaRecord.serializer)
      ..add(JavascriptRecord.serializer)
      ..add(JqueryRecord.serializer)
      ..add(KotlinRecord.serializer)
      ..add(LinuxRecord.serializer)
      ..add(MarketingRecord.serializer)
      ..add(MarketingmanagerRecord.serializer)
      ..add(MatlabRecord.serializer)
      ..add(MayaRecord.serializer)
      ..add(MechanicalRecord.serializer)
      ..add(NetRecord.serializer)
      ..add(NodejsRecord.serializer)
      ..add(OperationsRecord.serializer)
      ..add(PerlRecord.serializer)
      ..add(PhotoshopRecord.serializer)
      ..add(PhpRecord.serializer)
      ..add(PremiereRecord.serializer)
      ..add(ProductmanagerRecord.serializer)
      ..add(ProjectmanagerRecord.serializer)
      ..add(PythonRecord.serializer)
      ..add(ReactRecord.serializer)
      ..add(ResearchanalystRecord.serializer)
      ..add(RoboticsRecord.serializer)
      ..add(SaleforceRecord.serializer)
      ..add(SalesRecord.serializer)
      ..add(SalesmanagerRecord.serializer)
      ..add(SeleniumRecord.serializer)
      ..add(SoftwarearchitectRecord.serializer)
      ..add(SoftwaredevelopementengineerRecord.serializer)
      ..add(SoftwaredevelopementmanagerRecord.serializer)
      ..add(SqlRecord.serializer)
      ..add(SwiftRecord.serializer)
      ..add(SystemsecurityRecord.serializer)
      ..add(TensorflowRecord.serializer)
      ..add(TypescriptRecord.serializer)
      ..add(Unity3dRecord.serializer)
      ..add(UnrealRecord.serializer)
      ..add(UserRecord.serializer)
      ..add(VueRecord.serializer))
    .build();

// ignore_for_file: always_put_control_body_on_new_line,always_specify_types,annotate_overrides,avoid_annotating_with_dynamic,avoid_as,avoid_catches_without_on_clauses,avoid_returning_this,deprecated_member_use_from_same_package,lines_longer_than_80_chars,no_leading_underscores_for_local_identifiers,omit_local_variable_types,prefer_expression_function_bodies,sort_constructors_first,test_types_in_equals,unnecessary_const,unnecessary_new,unnecessary_lambdas
